<?php

use Illuminate\Database\Seeder;

class WashroomsTableSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('washrooms')->insert([
            'establishment_id'      => 1,
            'name'                  => 'Men\'s Washroom @ 5F',
            'location_description'  => '5th floor, near the elevators',
            'open_hours'            => '24 hours, Monday-Friday',
            'latitude'              => '14.554036',
            'longitude'             => '121.021707',
            'is_sponsored'          => true,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => true,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => true,
            'has_water'             => true,
            'has_soap'              => false,
            'has_shower'            => false,
            'has_wifi'              => true,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => false,
            'has_vending_machine'   => false,
            'has_diaper_station'    => false,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 1,
            'name'                  => 'Women\'s Washroom @ 5F',
            'location_description'  => '5th floor, near the elevators',
            'open_hours'            => '24 hours, Monday-Friday',
            'latitude'              => '14.554036',
            'longitude'             => '121.021707',
            'is_sponsored'          => true,
            'gender_is_female_only' => true,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => true,
            'has_water'             => true,
            'has_soap'              => false,
            'has_shower'            => false,
            'has_wifi'              => true,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => false,
            'has_vending_machine'   => false,
            'has_diaper_station'    => false,
        ]);
        
        DB::table('washrooms')->insert([
            'establishment_id'      => 2,
            'name'                  => 'Men\'s Washroom @ 3F',
            'location_description'  => 'Near the ATM Center',
            'open_hours'            => '9:00am to 10:00pm, Sunday-Saturday',
            'latitude'              => '14.5853246',
            'longitude'             => '121.0572364',
            'is_sponsored'          => false,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => true,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => true,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => true,
            'has_diaper_station'    => true,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 2,
            'name'                  => 'Women\'s Washroom @ 3F',
            'location_description'  => 'Near the ATM Center',
            'open_hours'            => '9:00am to 10:00pm, Sunday-Saturday',
            'latitude'              => '14.5853246',
            'longitude'             => '121.0572364',
            'is_sponsored'          => false,
            'gender_is_female_only' => true,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => true,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => true,
            'has_diaper_station'    => true,
        ]);


        DB::table('washrooms')->insert([
            'establishment_id'      => 8,
            'name'                  => 'Men\'s Washroom @ Lobby Area',
            'location_description'  => 'Near the Escalator',
            'open_hours'            => '24 Hours, Sunday to Saturday',
            'latitude'              => '14.5607705',
            'longitude'             => '121.0169363',
            'is_sponsored'          => false,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => true,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => false,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => true,
            'has_diaper_station'    => true,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 8,
            'name'                  => 'Women\'s Washroom @ Lobby Area',
            'location_description'  => 'Near the Escalator',
            'open_hours'            => '24 Hours, Sunday to Saturday',
            'latitude'              => '14.5607705',
            'longitude'             => '121.0169363',
            'is_sponsored'          => false,
            'gender_is_female_only' => true,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => false,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => true,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => true,
            'has_diaper_station'    => true,
        ]);


        DB::table('washrooms')->insert([
            'establishment_id'      => 4,
            'name'                  => 'Laboratory Washroom @ 1st Floor',
            'location_description'  => 'Near the Laboratory Reception',
            'open_hours'            => '24 Hours, Sunday to Saturday',
            'latitude'              => '14.5589173',
            'longitude'             => '121.0147846',
            'is_sponsored'          => false,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => true,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => true,
            'has_diaper_station'    => true,
        ]); 
        
        DB::table('washrooms')->insert([
            'establishment_id'      => 9,
            'name'                  => 'Men\'s Paid Washroom @ 3F',
            'location_description'  => 'Near H&M',
            'open_hours'            => '10:00am-10:00pm, Sunday-Saturday',
            'latitude'              => '14.7328507',
            'longitude'             => '121.0564181',
            'is_sponsored'          => false,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => true,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => false,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => false,
            'has_wifi'              => true,
            'has_tv'                => true,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => false,
            'has_diaper_station'    => true,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 9,
            'name'                  => 'Women\'s Paid Washroom @ 3F',
            'location_description'  => 'Near H&M',
            'open_hours'            => '10:00am-10:00pm, Sunday-Saturday',
            'latitude'              => '14.7328507',
            'longitude'             => '121.0564181',
            'is_sponsored'          => false,
            'gender_is_female_only' => true,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => false,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => false,
            'has_wifi'              => true,
            'has_tv'                => true,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => false,
            'has_diaper_station'    => true,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 10,
            'name'                  => 'Men\'s Washroom @ 2F',
            'location_description'  => 'Near Octagon',
            'open_hours'            => '11:00am-10:00pm, Sunday-Saturday',
            'latitude'              => '14.6603232',
            'longitude'             => '121.0290833',
            'is_sponsored'          => false,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => true,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => false,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => false,
            'is_pwd_friendly'       => false,
            'has_vending_machine'   => true,
            'has_diaper_station'    => false,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 10,
            'name'                  => 'Women\'s Washroom @ 2F',
            'location_description'  => 'Near Datablitz',
            'open_hours'            => '11:00am-10:00pm, Sunday-Saturday',
            'latitude'              => '14.6603232',
            'longitude'             => '121.0290833',
            'is_sponsored'          => false,
            'gender_is_female_only' => true,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => false,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => false,
            'is_pwd_friendly'       => false,
            'has_vending_machine'   => true,
            'has_diaper_station'    => false,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 6,
            'name'                  => 'Men\'s Washroom @ Food Court',
            'location_description'  => 'Near Jollibee',
            'open_hours'            => '11:00am-10:00pm, Sunday-Saturday',
            'latitude'              => '14.591892',
            'longitude'             => '121.058949',
            'is_sponsored'          => false,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => true,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => true,
            'has_diaper_station'    => false,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 6,
            'name'                  => 'Women\'s Washroom @ Food Court',
            'location_description'  => 'Near Sizzling Seafood',
            'open_hours'            => '11:00am-10:00pm, Sunday-Saturday',
            'latitude'              => '14.591892',
            'longitude'             => '121.058949',
            'is_sponsored'          => false,
            'gender_is_female_only' => true,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => true,
            'has_soap'              => true,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => true,
            'has_bidet'             => true,
            'is_pwd_friendly'       => true,
            'has_vending_machine'   => true,
            'has_diaper_station'    => false,
        ]);

        //--

        DB::table('washrooms')->insert([
            'establishment_id'      => 3,
            'name'                  => 'Men\'s Washroom @ 4F',
            'location_description'  => 'Near Jollibee',
            'open_hours'            => '9:00am to 10:00pm, Sunday-Saturday',
            'latitude'              => '14.5832028',
            'longitude'             => '121.0569799',
            'is_sponsored'          => false,
            'gender_is_female_only' => false,
            'gender_is_male_only'   => true,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => false,
            'need_membership'       => false,
            'has_water'             => false,
            'has_soap'              => false,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => false,
            'has_bidet'             => false,
            'is_pwd_friendly'       => false,
            'has_vending_machine'   => true,
            'has_diaper_station'    => false,
        ]);

        DB::table('washrooms')->insert([
            'establishment_id'      => 10,
            'name'                  => 'Women\'s Washroom @ 4F',
            'location_description'  => 'Near Burger King',
            'open_hours'            => '10:00am-10:00pm, Sunday-Saturday',
            'latitude'              => '14.6603232',
            'longitude'             => '121.0290833',
            'is_sponsored'          => false,
            'gender_is_female_only' => true,
            'gender_is_male_only'   => false,
            'gender_is_unisex'      => false,
            'gender_has_both'       => false,
            'is_free'               => true,
            'need_membership'       => false,
            'has_water'             => false,
            'has_soap'              => false,
            'has_shower'            => false,
            'has_wifi'              => false,
            'has_tv'                => false,
            'has_tissues'           => false,
            'has_bidet'             => false,
            'is_pwd_friendly'       => false,
            'has_vending_machine'   => false,
            'has_diaper_station'    => false,
        ]);
    }
}
